set_languages("c++20")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
target("test")
  set_kind("binary")
  add_files("source/**.cc")
  add_files("source/**.cpp")
  add_includedirs("source")
  add_includedirs("source/lib/v8/include")
  add_linkdirs("source/lib/v8/binary")
  add_links("v8_monolith")
  add_defines("V8_COMPRESS_POINTERS")
  add_defines("V8_ENABLE_SANDBOX")
  before_run(function (target)
    os.cp("$(curdir)/resource/config.toml", target:targetdir "/config.toml")
  end)