set_languages("c++20")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
target("test")
  set_kind("binary")
  set_symbols("debug", "hidden")
  add_rules("mode.debug")
  add_files("source/**.cc")
  add_files("source/**.cpp")
  add_includedirs("source")
  add_includedirs("source/lib/v8/include")
  add_linkdirs("source/lib/v8/binary")
  add_links("v8_monolith")
  add_defines("V8_COMPRESS_POINTERS")
  add_defines("V8_ENABLE_SANDBOX")
  set_runargs("config.toml")
  before_run(function (target)
    os.cp("$(curdir)/resource/config.toml", target:targetdir() .. "/config.toml")
    -- os.cp("service/**.js", target:targetdir() .. "/service/", {rootdir = "service"})
  end)