[core]
start_file = "main"
start_function = "start"
thread_size = 4
service_path = ""

[logging]
level = "DEBUG"
file_path = "/"

[gateway]
port = 8008

# [datasource]
# type = mysql
# url = "jdbc:mysql://192.168.0.1:3306/mydb"
# username = ""
# password = ""